// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB1SbUGm0-Ad0DMH2yDa5_w-AP6BESpfk',
    appId: '1:998584428063:web:a61d73d87cd863a0f0972a',
    messagingSenderId: '998584428063',
    projectId: 'yuhan-club-app',
    authDomain: 'yuhan-club-app.firebaseapp.com',
    storageBucket: 'yuhan-club-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsfj3iWN5jAEV07YfJd97rgXSjJwOWA4A',
    appId: '1:998584428063:android:7d16bc4a48ccf59bf0972a',
    messagingSenderId: '998584428063',
    projectId: 'yuhan-club-app',
    storageBucket: 'yuhan-club-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy_B79xl9D0y-clwsDLoQ_X1AoTUWYRMc',
    appId: '1:998584428063:ios:ff75b72edddc686af0972a',
    messagingSenderId: '998584428063',
    projectId: 'yuhan-club-app',
    storageBucket: 'yuhan-club-app.firebasestorage.app',
    iosBundleId: 'kr.ac.yuhan.yuhanClub',
  );
}
